//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBooksClient_991471961.BookReference_991471961 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookInfo", Namespace="http://schemas.datacontract.org/2004/07/ABCBooksService_991471961")]
    [System.SerializableAttribute()]
    public partial class BookInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageCount {
            get {
                return this.PageCountField;
            }
            set {
                if ((this.PageCountField.Equals(value) != true)) {
                    this.PageCountField = value;
                    this.RaisePropertyChanged("PageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookReference_991471961.IBookService_991471961")]
    public interface IBookService_991471961 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetAllBooks", ReplyAction="http://tempuri.org/IBookService_991471961/GetAllBooksResponse")]
        ABCBooksClient_991471961.BookReference_991471961.BookInfo[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetAllBooks", ReplyAction="http://tempuri.org/IBookService_991471961/GetAllBooksResponse")]
        System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetABook", ReplyAction="http://tempuri.org/IBookService_991471961/GetABookResponse")]
        ABCBooksClient_991471961.BookReference_991471961.BookInfo GetABook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetABook", ReplyAction="http://tempuri.org/IBookService_991471961/GetABookResponse")]
        System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo> GetABookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetABookByISBN", ReplyAction="http://tempuri.org/IBookService_991471961/GetABookByISBNResponse")]
        ABCBooksClient_991471961.BookReference_991471961.BookInfo GetABookByISBN(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetABookByISBN", ReplyAction="http://tempuri.org/IBookService_991471961/GetABookByISBNResponse")]
        System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo> GetABookByISBNAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetABookByTitle", ReplyAction="http://tempuri.org/IBookService_991471961/GetABookByTitleResponse")]
        ABCBooksClient_991471961.BookReference_991471961.BookInfo GetABookByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetABookByTitle", ReplyAction="http://tempuri.org/IBookService_991471961/GetABookByTitleResponse")]
        System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo> GetABookByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetABookByAuthor", ReplyAction="http://tempuri.org/IBookService_991471961/GetABookByAuthorResponse")]
        ABCBooksClient_991471961.BookReference_991471961.BookInfo GetABookByAuthor(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/GetABookByAuthor", ReplyAction="http://tempuri.org/IBookService_991471961/GetABookByAuthorResponse")]
        System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo> GetABookByAuthorAsync(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/EditBook", ReplyAction="http://tempuri.org/IBookService_991471961/EditBookResponse")]
        void EditBook(ABCBooksClient_991471961.BookReference_991471961.BookInfo book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/EditBook", ReplyAction="http://tempuri.org/IBookService_991471961/EditBookResponse")]
        System.Threading.Tasks.Task EditBookAsync(ABCBooksClient_991471961.BookReference_991471961.BookInfo book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/AddBook", ReplyAction="http://tempuri.org/IBookService_991471961/AddBookResponse")]
        void AddBook(ABCBooksClient_991471961.BookReference_991471961.BookInfo book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/AddBook", ReplyAction="http://tempuri.org/IBookService_991471961/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(ABCBooksClient_991471961.BookReference_991471961.BookInfo book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/DeleteBook", ReplyAction="http://tempuri.org/IBookService_991471961/DeleteBookResponse")]
        void DeleteBook(ABCBooksClient_991471961.BookReference_991471961.BookInfo book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService_991471961/DeleteBook", ReplyAction="http://tempuri.org/IBookService_991471961/DeleteBookResponse")]
        System.Threading.Tasks.Task DeleteBookAsync(ABCBooksClient_991471961.BookReference_991471961.BookInfo book);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookService_991471961Channel : ABCBooksClient_991471961.BookReference_991471961.IBookService_991471961, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookService_991471961Client : System.ServiceModel.ClientBase<ABCBooksClient_991471961.BookReference_991471961.IBookService_991471961>, ABCBooksClient_991471961.BookReference_991471961.IBookService_991471961 {
        
        public BookService_991471961Client() {
        }
        
        public BookService_991471961Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookService_991471961Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookService_991471961Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookService_991471961Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ABCBooksClient_991471961.BookReference_991471961.BookInfo[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public ABCBooksClient_991471961.BookReference_991471961.BookInfo GetABook(int id) {
            return base.Channel.GetABook(id);
        }
        
        public System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo> GetABookAsync(int id) {
            return base.Channel.GetABookAsync(id);
        }
        
        public ABCBooksClient_991471961.BookReference_991471961.BookInfo GetABookByISBN(string isbn) {
            return base.Channel.GetABookByISBN(isbn);
        }
        
        public System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo> GetABookByISBNAsync(string isbn) {
            return base.Channel.GetABookByISBNAsync(isbn);
        }
        
        public ABCBooksClient_991471961.BookReference_991471961.BookInfo GetABookByTitle(string title) {
            return base.Channel.GetABookByTitle(title);
        }
        
        public System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo> GetABookByTitleAsync(string title) {
            return base.Channel.GetABookByTitleAsync(title);
        }
        
        public ABCBooksClient_991471961.BookReference_991471961.BookInfo GetABookByAuthor(string author) {
            return base.Channel.GetABookByAuthor(author);
        }
        
        public System.Threading.Tasks.Task<ABCBooksClient_991471961.BookReference_991471961.BookInfo> GetABookByAuthorAsync(string author) {
            return base.Channel.GetABookByAuthorAsync(author);
        }
        
        public void EditBook(ABCBooksClient_991471961.BookReference_991471961.BookInfo book) {
            base.Channel.EditBook(book);
        }
        
        public System.Threading.Tasks.Task EditBookAsync(ABCBooksClient_991471961.BookReference_991471961.BookInfo book) {
            return base.Channel.EditBookAsync(book);
        }
        
        public void AddBook(ABCBooksClient_991471961.BookReference_991471961.BookInfo book) {
            base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(ABCBooksClient_991471961.BookReference_991471961.BookInfo book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public void DeleteBook(ABCBooksClient_991471961.BookReference_991471961.BookInfo book) {
            base.Channel.DeleteBook(book);
        }
        
        public System.Threading.Tasks.Task DeleteBookAsync(ABCBooksClient_991471961.BookReference_991471961.BookInfo book) {
            return base.Channel.DeleteBookAsync(book);
        }
    }
}
